### ISSUE TITLE
mnemosyne-ruby and sentry-raven are incompatible

### ISSUE THREAD

**Issue by MrSerth** [mnemosyne-mon/mnemosyne-ruby#17]
The current version of mnemosyne-ruby and sentry-rave in version 3.0.0 are incompatible, probably due to the faraday version jump from 0.* to 1.* Therefore, Sentry does not receive any events. 

``` ruby
2.6.0 :001 > Raven.capture do
2.6.0 :002 >       # capture any exceptions which happen during execution of this block
2.6.0 :003 >       1 / 0
2.6.0 :004?>   end
Traceback (most recent call last):
Sending event 015e79abe6da450f949108b16c33d93e to Sentry
        3: from (irb):1
        2: from (irb):3:in `block in irb_binding'
        1: from (irb):3:in `/'
ZeroDivisionError (divided by 0)
2.6.0 :005 > Raven HTTP Transport connecting to [URL]
Unable to record event with remote Sentry server (NoMethodError - undefined method `ancestors' for Faraday::Response::RaiseError:Faraday::RackBuilder::Handler):
/var/www/app/shared/bundle/ruby/2.6.0/gems/faraday-1.0.0/lib/faraday/rack_builder.rb:234:in `is_adapter?'
/var/www/app/shared/bundle/ruby/2.6.0/gems/mnemosyne-ruby-1.9.0/lib/mnemosyne/probes/faraday/base.rb:22:in `block in lock!'
/var/www/app/shared/bundle/ruby/2.6.0/gems/mnemosyne-ruby-1.9.0/lib/mnemosyne/probes/faraday/base.rb:22:in `find_index'
/var/www/app/shared/bundle/ruby/2.6.0/gems/mnemosyne-ruby-1.9.0/lib/mnemosyne/probes/faraday/base.rb:22:in `lock!'
/var/www/app/shared/bundle/ruby/2.6.0/gems/faraday-1.0.0/lib/faraday/rack_builder.rb:165:in `app'
/var/www/app/shared/bundle/ruby/2.6.0/gems/faraday-1.0.0/lib/faraday/rack_builder.rb:153:in `build_response'
/var/www/app/shared/bundle/ruby/2.6.0/gems/faraday-1.0.0/lib/faraday/connection.rb:492:in `run_request'
/var/www/app/shared/bundle/ruby/2.6.0/gems/faraday-1.0.0/lib/faraday/connection.rb:279:in `post'
/var/www/app/shared/bundle/ruby/2.6.0/gems/sentry-raven-3.0.0/lib/raven/transports/http.rb:24:in `send_event'
/var/www/app/shared/bundle/ruby/2.6.0/gems/sentry-raven-3.0.0/lib/raven/client.rb:44:in `send_event'
/var/www/app/shared/bundle/ruby/2.6.0/gems/sentry-raven-3.0.0/lib/raven/instance.rb:81:in `send_event'
Failed to submit event: <no message value>
```

**Comment by jgraichen** [comment]
Please test with `1.10.0.beta1`.

**Comment by MrSerth** [comment]
Thanks for your release. It's working again as expected. ;)

**Comment by jgraichen** [comment]
Thanks. Release final `1.10.0` just now.
